source 'https://rubygems.org'

ruby '2.7.3'
gem 'rails', '5.2.6'

gem 'pg', '1.1.4'

# gem 'mysql2' # for data migration

gem 'sass'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jquery-ui-themes'
gem 'jquery-infinite-pages'
gem 'jbuilder', '~> 2.5'

gem 'acts-as-taggable-on' #, '~> 3.4'
gem 'auto_html'
gem 'bcrypt_pbkdf'
gem 'bulma-rails', ref: '30249b7'
gem 'capistrano'
gem 'capistrano-rails'#, '1.1.3'
gem 'capistrano-rvm'
gem 'capistrano-bundler'#, '1.1.4'
gem 'capistrano3-puma'

gem 'cancancan'
gem 'carrierwave'
gem 'carrierwave-aws'
gem 'chosen-rails'
gem 'closure_tree'
gem 'ckeditor'# , '4.3.0' #, github: 'galetahub/ckeditor', branch: 'master'
#gem 'compass-rails'#, '~> 2.0.alpha.0'
gem 'countries'
gem 'country_select'
gem 'devise'
gem 'ed25519'
gem 'etherpad-lite'
gem 'event-calendar', :require => 'event_calendar'
gem 'fast_jsonapi'
gem 'figaro'
gem 'flickraw'
gem 'flickr_fu'
gem 'font-awesome-rails'
gem 'formtastic'#, '~> 2.3.0.rc2'
gem 'foundation-rails', '6.2.4.0'
gem 'friendly_id', '~> 5.1.0'
gem 'friendly_id-globalize'
gem 'geocoder'
gem 'gibbon'
gem 'globalize', github: 'globalize/globalize', branch: 'master'
# gem "globalize", github: "ncri/globalize"
gem 'haml-rails'
gem 'handles_sortable_columns', github: 'cenotaph/handles_sortable_columns'
gem 'has_scope'
# gem 'hominid'
gem 'http_accept_language'
#gem 'inherited_resources' #, github: 'josevalim/inherited_resources'
# gem "jquery-slick-rails"
gem 'lazybox'
gem 'kaminari'
gem 'mail_form'
gem 'meta-tags', require: 'meta_tags'
gem 'mini_magick'
gem 'nested_form'
gem "non-stupid-digest-assets"
gem 'oauth-client'
gem 'omniauth-facebook' #, '1.4.0'
gem 'omniauth-google-oauth2'
gem 'omniauth-twitter'
gem 'paper_trail' #, '~> 3.0.6'
gem 'puma', '5.5.1', group: :production
gem 'rack-utf8_sanitizer'
gem 'rack-cors', require: 'rack/cors'
gem 'rails-jquery-autocomplete'
# gem 'rails3-jquery-autocomplete', github: 'crowdint/rails3-jquery-autocomplete'
gem 'randumb'
gem "recaptcha", '3.0', require: "recaptcha/rails"
gem 'redis-rails', '~> 5.0.1'
gem 'redis'
gem 'rest-client'
gem 'rolify'
gem 'rollbar'
gem 'shog'
gem 'slick_rails'

gem 'textacular'# , '~> 4.0'
gem 'themes_for_rails', github: 'cenotaph/themes_for_rails', branch: 'master'

gem 'truncate_html'
gem 'twitter'

gem 'unf' 
gem 'vimeo'
gem 'xmlrpc'
gem 'yt'
# gem 'youtube_it'

group :development do
  gem 'better_errors', github: 'workingnotworking/better_errors'
  gem 'binding_of_caller'
  gem 'letter_opener'
  gem 'listen', '~> 3.0.5'
  gem 'ruby_parser', '>= 3.0.1'
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'unicorn'
end
