source 'https://rubygems.org'
ruby '2.2.0'
gem 'rails', '4.2.0'
gem 'pg'
gem 'mysql2' # for data migration

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jquery-ui-themes'
gem 'jbuilder', '~> 1.2'
gem 'execjs', :group => :production
# gem 'therubyracer', :group => :production

gem 'acts-as-taggable-on', '~> 3.4'
gem 'auto_html'
gem 'capistrano', '~> 3.1.0'
gem 'capistrano-rails', '~> 1.1.0'
gem 'capistrano-rvm'
gem 'capistrano-bundler'
gem 'cancancan'
gem 'carrierwave'
gem 'carrierwave-aws'
gem 'chosen-rails'
gem 'closure_tree'
gem 'ckeditor' #, github: 'galetahub/ckeditor', branch: 'master'
gem 'compass-rails'#, '~> 2.0.alpha.0'
gem 'country_select'
gem 'devise'
gem 'etherpad-lite'
gem 'event-calendar', :require => 'event_calendar'
gem 'figaro'
gem 'flickraw'

gem 'font-awesome-rails'
gem 'formtastic', '~> 2.3.0.rc2'
gem 'foundation-rails', '5.3.0'
gem 'friendly_id'
gem 'friendly_id-globalize'
gem 'geocoder'
gem 'globalize', github: 'globalize/globalize', branch: 'master'
gem 'haml-rails'
gem 'handles_sortable_columns'
gem 'has_scope'
gem 'hominid'
gem 'http_accept_language'
gem 'inherited_resources', github: 'josevalim/inherited_resources'
gem "jquery-slick-rails"
gem 'lazybox'
gem 'kaminari'
gem 'meta-tags', require: 'meta_tags'
gem 'mini_magick'
gem 'nested_form'
gem "non-stupid-digest-assets"
gem 'oauth-client'
gem 'omniauth-facebook' #, '1.4.0'
gem 'omniauth-google-oauth2'
gem 'omniauth-twitter'
gem 'paper_trail', '~> 3.0.6'
gem 'rails4-autocomplete'
# gem 'rails3-jquery-autocomplete', github: 'crowdint/rails3-jquery-autocomplete'
gem 'randumb'
gem 'recaptcha'
gem 'rolify'
gem 'shog'
gem 'textacular', branch: :master, github: 'textacular/textacular'
gem 'themes_for_rails', github: 'boxcar21/themes_for_rails', branch: 'master'
gem 'truncate_html'
gem 'unicorn'
gem 'unf' 
gem 'vimeo'
gem 'youtube_it'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'#, :platforms=>[:mri_19, :mri_20, :rbx]
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'html2haml'
  gem 'hub', :require => nil
  gem 'letter_opener'
  gem 'nifty-generators'
  gem 'rails-footnotes',  '>= 3.7.9'
  gem 'quiet_assets'
  gem 'rb-fchange', :require=>false
  gem 'rb-fsevent', :require=>false
  gem 'rb-inotify', :require=>false
  gem 'spring'
  gem 'byebug'
  # gem 'web-console'
end
group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
end
group :test do
  gem 'faker'
  gem 'capybara'
  gem 'database_cleaner', '1.0.1'
  gem 'email_spec'
  gem 'railroady'
end
